Cleanup & Test framework
Formal-Systems-Laboratory/ROSRV pull request #3
Opened 2019-07-30 17:24 UTC by nishantjr

2019-08-01 14:00 UTC, msaxena2 reviewed
I was thinking of getting rid of the original dependency on rostopic altogether, which would've required dependence on live* files. This is fine too, since it cleans up testing.

2019-08-01 15:13 UTC, nishantjr commented
Okay. Any particular reason for getting rid of `rostopic`? Otherwise, did you approve? Can we merge this?

2019-08-01 17:41 UTC, msaxena2 commented on src/RVMaster/rvmonitor.rv
> +}
Should this file be placed under some sort of `test` folder to indicate it's only meant to be used as a test spec?

2019-08-01 17:48 UTC, msaxena2 commented on src/monitors/CMakeLists.txt
> +
delete the commented out parts?

2019-08-01 17:53 UTC, msaxena2 commented on Test
> +export ACCESS_POLICY_PATH=/home/njr/AA/ext/ROSRV/config/access-policy.cfg
Is this path intentionally hardcoded?

2019-08-01 17:55 UTC, msaxena2 commented on Test
> +progress() { echo ==== "$@" ; }
line 5 uses progress. On my machine, running `./Test` throws `progress:Command not found`. Perhaps moving the definition above line 5 will fix this issue.

2019-08-01 17:58 UTC, msaxena2 commented on Test
> +
I simply got a `pytest command not found error` instead of the above mentioned message. Not sure why.

2019-08-01 18:00 UTC, msaxena2 requested changes
Looks good apart from the few minor issues.

2019-08-01 18:03 UTC, msaxena2 commented
> Okay. Any particular reason for getting rid of `rostopic`? Otherwise, did you approve? Can we merge this?

Rostopic isn't bundled with the minimal ROS installation, as far as I could tell. The only motivation was to depend on basic ROS.

2019-08-01 19:56 UTC, nishantjr commented
Well, at the moment rvmaster cannot be built without it. Therefore it is
not test code. I will fix that in the next few PRs.

On Thu, 1 Aug, 2019, 12:41 Manasvi Saxena, <notifications@github.com> wrote:

> *@msaxena2* commented on this pull request.
> ------------------------------
>
> In src/RVMaster/rvmonitor.rv
> <https://github.com/Formal-Systems-Laboratory/ROSRV/pull/3#discussion_r309817669>
> :
>
> > @@ -0,0 +1,14 @@
> +#include <cstring>
> +#include <string>
> +#include "ros/ros.h"
> +
> +testSpecOne() {
> +    int a = 10;
> +    int b;
> +
> +    event controlMessageOne(std::string msg) /chatter std_msgs/String '{data:msg}'
> +    {
> +        msg = msg + "RV";
> +        ROS_INFO("%s", msg.c_str());
> +    }
> +}
>
> Should this file be placed under some sort of test folder to indicate
> it's only meant to be used as a test spec?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Formal-Systems-Laboratory/ROSRV/pull/3?email_source=notifications&email_token=AAE3ABL4ZCYSLT6DWNM2TUTQCMN5TA5CNFSM4IH6TG2KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCAKHHOY#pullrequestreview-269775803>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAE3ABJABKZGPWYHEPEQHTTQCMN5TANCNFSM4IH6TG2A>
> .
>

2019-08-01 19:56 UTC, nishantjr commented
Ok. This is only for testing so should be fine.

On Thu, 1 Aug, 2019, 13:03 Manasvi Saxena, <notifications@github.com> wrote:

> Okay. Any particular reason for getting rid of rostopic? Otherwise, did
> you approve? Can we merge this?
>
> Rostopic isn't bundled with the minimal ROS installation, as far as I
> could tell. The only motivation was to depend on basic ROS.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Formal-Systems-Laboratory/ROSRV/pull/3?email_source=notifications&email_token=AAE3ABMJ6JKISQ656QAL67LQCMQN7A5CNFSM4IH6TG2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3LNNJY#issuecomment-517396135>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAE3ABIZSKY26YTQHFABG6DQCMQN7ANCNFSM4IH6TG2A>
> .
>

2019-08-13 09:48 UTC, msaxena2 commented
lgtm.

2019-08-13 09:51 UTC, msaxena2 approved these changes

2019-08-13 14:15 UTC, merged